site_name: 'Devops'
site_description: 'Main documentation for Backstage Circle CI features and platform APIs'
repo_url:  https://github.com/dhanu0001/samplerepo
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  
nav:
  - Introduction: index.md
